#!/usr/bin/env python3
"""Emit reconcile-roles.sh from The Last Exam's published role manifest.

Usage: python3 generate.py <role-manifest.json> [reconcile-roles.sh]

The manifest is deployment information published by the TLE server repo
(deploy-info/role-manifest.json there). Regenerate whenever it changes.
"""
import json
import sys
from pathlib import Path

if len(sys.argv) not in (2, 3):
    sys.exit(__doc__.split("\n\n")[1])
manifest_path = Path(sys.argv[1])
out = Path(sys.argv[2]) if len(sys.argv) == 3 else Path(__file__).with_name("reconcile-roles.sh")
m = json.loads(manifest_path.read_text())

cap_lines = "\n".join(
    f"{c['name']}|TLE capability ({'+'.join(c['access'])}): {', '.join(c['tools'])}"
    for c in m["capabilities"]
)
bundle_desc = "\n".join(f"{c['name']}|{c['description']}" for c in m["composites"])
members = "\n".join(
    f"{c['name']}|{name}" for c in m["composites"] for name in c["capabilities"]
)
for text in (cap_lines, bundle_desc, members):
    assert "'" not in text, "single quote would break the sh literal"

script = f"""#!/bin/sh
# Reconcile the TLE operator client and its roles in the Keycloak "homelab" realm.
#
# Generated by generate.py from The Last Exam's role manifest
#   (manifest_version {m['manifest_version']}, registry schema {m['registry_schema_version']},
#    {len(m['capabilities'])} capabilities, composites: {', '.join(c['name'] + '=' + str(len(c['capabilities'])) for c in m['composites'])}).
# Do not edit this file by hand; rerun generate.py with the new manifest.
#
# What it does (only adds; never removes anything except step 4):
#   1. Ensures a confidential OIDC client "tle-operator" exists (standard flow only,
#      no redirect URIs yet; those come with the admin-portal sign-in work).
#   2. Ensures one client role per capability exists on it.
#   3. Ensures client roles support / operator / admin exist and hold at least
#      the manifest's members (flattened). Extra members are reported, not removed.
#   4. Deletes the unused REALM roles "support" and "operator", but only if they are
#      not composite, not assigned to any user or group, and not in the default roles.
#      The realm role "admin" (homelab administrator) is never touched.
#   5. Verifies the result against the manifest; exits 1 on any drift.
#
# Runs inside the Keycloak pod with the bootstrap admin credentials already in its
# environment; the password never leaves the pod or appears in arguments.
#
#   Dry run (default, read-only):
#     sg k3s-admin -c 'KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl -n keycloak exec -i deploy/keycloak -- sh -s' < platform/keycloak/tle-operator/reconcile-roles.sh
#   Apply:
#     sg k3s-admin -c 'KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl -n keycloak exec -i deploy/keycloak -- sh -s apply' < platform/keycloak/tle-operator/reconcile-roles.sh
set -eu

MODE=${{1:-dry-run}}
case "$MODE" in
  dry-run|apply) ;;
  *) echo "usage: sh -s [dry-run|apply]" >&2; exit 2 ;;
esac

REALM=homelab
CLIENT_ID=tle-operator
CLIENT_NAME='The Last Exam operators'
K=/opt/keycloak/bin/kcadm.sh
W=$(mktemp -d)
C=$W/kcadm.config
trap 'rm -rf "$W"' EXIT

CAPABILITIES='
{cap_lines}
'

BUNDLES='
{bundle_desc}
'

# bundle|capability, flattened (includes already resolved by the manifest).
MEMBERS='
{members}
'

# kcadm never gets the script's stdin: this script itself arrives on stdin.
kc() {{ "$K" "$@" -r "$REALM" --config "$C" </dev/null; }}
kc_body() {{ "$K" "$@" -r "$REALM" --config "$C"; }}

# Run a mutation in apply mode; only describe it in dry-run mode.
change() {{
  msg=$1; shift
  if [ "$MODE" = apply ]; then
    echo "apply: $msg"
    "$@" >/dev/null
  else
    echo "would: $msg"
  fi
}}

lines() {{ printf '%s\\n' "$1" | grep -v '^$'; }}

KC_CLI_PASSWORD="$KC_BOOTSTRAP_ADMIN_PASSWORD" "$K" config credentials \\
  --server http://localhost:8080 --realm master \\
  --user "$KC_BOOTSTRAP_ADMIN_USERNAME" --config "$C" >/dev/null
echo "mode: $MODE, realm: $REALM, client: $CLIENT_ID"

lines "$CAPABILITIES" | cut -d'|' -f1 | sort > "$W/want-caps"
lines "$BUNDLES" | cut -d'|' -f1 | sort > "$W/want-bundles"
sort "$W/want-caps" "$W/want-bundles" > "$W/want-roles"

# --- 1. client -------------------------------------------------------------
client_uuid() {{
  # Exact match on clientId; duplicates abort.
  kc get clients -q "clientId=$CLIENT_ID" --fields id,clientId --format csv --noquotes \\
    | grep ",$CLIENT_ID\\$" | cut -d, -f1 > "$W/client"
  n=$(wc -l < "$W/client")
  if [ "$n" -gt 1 ]; then echo "duplicate clients named $CLIENT_ID" >&2; exit 1; fi
  cat "$W/client"
}}

CU=$(client_uuid)
if [ -z "$CU" ]; then
  change "create confidential client $CLIENT_ID" kc create clients \\
    -s "clientId=$CLIENT_ID" -s "name=$CLIENT_NAME" -s protocol=openid-connect \\
    -s enabled=true -s publicClient=false -s clientAuthenticatorType=client-secret \\
    -s standardFlowEnabled=true -s implicitFlowEnabled=false \\
    -s directAccessGrantsEnabled=false -s serviceAccountsEnabled=false \\
    -s 'redirectUris=[]' -s 'webOrigins=[]'
  [ "$MODE" = apply ] && CU=$(client_uuid)
else
  echo "ok: client $CLIENT_ID exists"
fi

current_roles() {{
  if [ -n "$CU" ]; then
    kc get "clients/$CU/roles" --fields name --format csv --noquotes | sort
  fi
}}

# --- 2 + 3a. capability and bundle roles ------------------------------------
current_roles > "$W/have-roles"
{{ lines "$CAPABILITIES"; lines "$BUNDLES"; }} | while IFS='|' read -r name desc; do
  if grep -Fxq "$name" "$W/have-roles"; then continue; fi
  change "create client role $name" kc create "clients/$CU/roles" -s "name=$name" -s "description=$desc"
done
current_roles > "$W/have-roles"
grep -Fxv -f "$W/want-roles" "$W/have-roles" > "$W/extra-roles" || true
while read -r name; do echo "WARN: client role $name is not in the manifest (left in place)"; done < "$W/extra-roles"

# --- 3b. composite members ---------------------------------------------------
role_id() {{
  kc get "clients/$CU/roles/$1" --fields id --format csv --noquotes
}}

while read -r bundle; do
  lines "$MEMBERS" | grep "^$bundle|" | cut -d'|' -f2 | sort > "$W/want-$bundle"
  if [ -n "$CU" ] && grep -Fxq "$bundle" "$W/have-roles"; then
    kc get "clients/$CU/roles/$bundle/composites" --fields name --format csv --noquotes | sort > "$W/have-$bundle"
  else
    : > "$W/have-$bundle"
  fi
  grep -Fxv -f "$W/have-$bundle" "$W/want-$bundle" > "$W/missing-$bundle" || true
  grep -Fxv -f "$W/want-$bundle" "$W/have-$bundle" > "$W/extra-$bundle" || true
  missing=$(wc -l < "$W/missing-$bundle")
  if [ "$missing" -eq 0 ]; then
    echo "ok: $bundle holds all $(wc -l < "$W/want-$bundle") members"
  elif [ "$MODE" = apply ]; then
    body='['
    sep=
    while read -r cap; do
      body="$body$sep{{\\"id\\":\\"$(role_id "$cap")\\",\\"name\\":\\"$cap\\"}}"
      sep=,
    done < "$W/missing-$bundle"
    body="$body]"
    echo "apply: add $missing members to composite $bundle"
    printf '%s' "$body" | kc_body create "clients/$CU/roles/$bundle/composites" -f - >/dev/null
  else
    echo "would: add $missing members to composite $bundle"
  fi
  while read -r name; do echo "WARN: composite $bundle has extra member $name (left in place)"; done < "$W/extra-$bundle"
done < "$W/want-bundles"

# --- 4. unused realm roles ---------------------------------------------------
kc get roles --fields name --format csv --noquotes > "$W/realm-roles"
kc get "roles/default-roles-$REALM/composites" --fields name --format csv --noquotes > "$W/default-roles" 2>/dev/null || : > "$W/default-roles"
for r in support operator; do
  if ! grep -Fxq "$r" "$W/realm-roles"; then echo "ok: no realm role $r"; continue; fi
  composite=$(kc get "roles/$r" --fields composite --format csv --noquotes)
  users=$(kc get "roles/$r/users" --fields id --format csv --noquotes | grep -c . || true)
  groups=$(kc get "roles/$r/groups" --fields id --format csv --noquotes | grep -c . || true)
  if [ "$composite" != false ] || [ "$users" -ne 0 ] || [ "$groups" -ne 0 ] || grep -Fxq "$r" "$W/default-roles"; then
    echo "SKIP: realm role $r is in use (composite=$composite users=$users groups=$groups); remove it by hand if intended"
  else
    change "delete unused realm role $r" kc delete "roles/$r"
  fi
done

# --- 5. verify -----------------------------------------------------------------
if [ "$MODE" = dry-run ]; then
  echo "dry run complete; nothing was changed"
  exit 0
fi
status=0
current_roles > "$W/have-roles"
if grep -Fxv -f "$W/have-roles" "$W/want-roles" > "$W/still-missing"; then
  echo "FAIL: roles still missing: $(tr '\\n' ' ' < "$W/still-missing")"; status=1
fi
while read -r bundle; do
  kc get "clients/$CU/roles/$bundle/composites" --fields name --format csv --noquotes | sort > "$W/have-$bundle"
  if [ "$(cat "$W/want-$bundle")" != "$(cat "$W/have-$bundle")" ]; then
    echo "FAIL: composite $bundle differs from the manifest"; status=1
  fi
done < "$W/want-bundles"
[ "$status" -eq 0 ] && echo "verified: $(wc -l < "$W/want-caps") capability roles and $(wc -l < "$W/want-bundles") composites match the manifest"
exit "$status"
"""
out.write_text(script)
print(f"wrote {out}")
