#!/bin/sh
# Reconcile the TLE operator client and its roles in the Keycloak "homelab" realm.
#
# Generated by generate.py from The Last Exam's role manifest
#   (manifest_version 1, registry schema 1.3,
#    64 capabilities, composites: support=14, operator=44, admin=64).
# Do not edit this file by hand; rerun generate.py with the new manifest.
#
# What it does (only adds; never removes anything except step 4):
#   1. Ensures a confidential OIDC client "tle-operator" exists (standard flow only,
#      no redirect URIs yet; those come with the admin-portal sign-in work).
#   2. Ensures one client role per capability exists on it.
#   3. Ensures client roles support / operator / admin exist and hold at least
#      the manifest's members (flattened). Extra members are reported, not removed.
#   4. Deletes the unused REALM roles "support" and "operator", but only if they are
#      not composite, not assigned to any user or group, and not in the default roles.
#      The realm role "admin" (homelab administrator) is never touched.
#   5. Verifies the result against the manifest; exits 1 on any drift.
#
# Runs inside the Keycloak pod with the bootstrap admin credentials already in its
# environment; the password never leaves the pod or appears in arguments.
#
#   Dry run (default, read-only):
#     sg k3s-admin -c 'KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl -n keycloak exec -i deploy/keycloak -- sh -s' < platform/keycloak/tle-operator/reconcile-roles.sh
#   Apply:
#     sg k3s-admin -c 'KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl -n keycloak exec -i deploy/keycloak -- sh -s apply' < platform/keycloak/tle-operator/reconcile-roles.sh
set -eu

MODE=${1:-dry-run}
case "$MODE" in
  dry-run|apply) ;;
  *) echo "usage: sh -s [dry-run|apply]" >&2; exit 2 ;;
esac

REALM=homelab
CLIENT_ID=tle-operator
CLIENT_NAME='The Last Exam operators'
K=/opt/keycloak/bin/kcadm.sh
W=$(mktemp -d)
C=$W/kcadm.config
trap 'rm -rf "$W"' EXIT

CAPABILITIES='
admin.auth.api_keys.manage|TLE capability (write): auth-administration
admin.auth.keys.rotate|TLE capability (write): auth-administration
admin.auth.kill_switch|TLE capability (write): auth-administration
admin.auth.read|TLE capability (read): auth-administration
admin.auth.sessions.read|TLE capability (read): auth-administration
admin.auth.sessions.revoke|TLE capability (write): auth-administration
admin.game.match.terminate|TLE capability (write): game-pod-administration
admin.game.read|TLE capability (read): game-pod-administration
admin.game.snapshot.read|TLE capability (read): game-pod-administration
admin.gamemaster.capacity.write|TLE capability (write): game-master-administration
admin.gamemaster.pod.drain|TLE capability (write): game-master-administration
admin.gamemaster.read|TLE capability (read): game-master-administration
admin.gateway.policy.write|TLE capability (write): gateway-security-operations
admin.gateway.read|TLE capability (read): gateway-security-operations
admin.k8s.drain|TLE capability (write): kubernetes-operations
admin.k8s.logs.read|TLE capability (read): kubernetes-operations
admin.k8s.read|TLE capability (read): kubernetes-operations
admin.k8s.restart|TLE capability (write): kubernetes-operations
admin.k8s.scale|TLE capability (write): kubernetes-operations
admin.lobby.moderate|TLE capability (write): lobby-administration
admin.lobby.read|TLE capability (read): lobby-administration
admin.lobby.session.disconnect|TLE capability (write): lobby-administration
admin.matchmaking.queue.intervene|TLE capability (write): matchmaking-administration
admin.matchmaking.read|TLE capability (read): matchmaking-administration
admin.matchmaking.replay|TLE capability (write): matchmaking-administration
admin.metadata.activate|TLE capability (write): metadata-administration
admin.metadata.dependency.write|TLE capability (write): metadata-administration
admin.metadata.entity.create|TLE capability (write): metadata-administration
admin.metadata.entity.delete|TLE capability (write): metadata-administration
admin.metadata.entity.update|TLE capability (write): metadata-administration
admin.metadata.publish|TLE capability (write): metadata-administration
admin.metadata.read|TLE capability (read): metadata-administration
admin.metadata.retire|TLE capability (write): metadata-administration
admin.metadata.validate|TLE capability (write): metadata-administration
admin.nats.consumer.manage|TLE capability (write): nats-administration
admin.nats.read|TLE capability (read): nats-administration
admin.nats.replay|TLE capability (write): nats-administration
admin.notification.preference.write|TLE capability (write): notification-administration
admin.notification.read|TLE capability (read): notification-administration
admin.notification.replay|TLE capability (write): notification-administration
admin.notification.template.write|TLE capability (write): notification-administration
admin.player.economy.adjust|TLE capability (write): player-administration
admin.player.inventory.adjust|TLE capability (write): player-administration
admin.player.progression.adjust|TLE capability (write): player-administration
admin.player.read|TLE capability (read): player-administration
admin.quest.compensation.resolve|TLE capability (write): quest-administration
admin.quest.control.write|TLE capability (write): quest-administration
admin.quest.definition.activate|TLE capability (write): quest-administration
admin.quest.definition.create|TLE capability (write): quest-administration
admin.quest.definition.delete|TLE capability (write): quest-administration
admin.quest.definition.publish|TLE capability (write): quest-administration
admin.quest.definition.update|TLE capability (write): quest-administration
admin.quest.migration.execute|TLE capability (write): quest-administration
admin.quest.quarantine.replay|TLE capability (write): quest-administration
admin.quest.read|TLE capability (read): quest-administration
admin.security.rate_limit.write|TLE capability (write): gateway-security-operations
admin.social.guild.manage|TLE capability (write): social-administration
admin.social.moderate|TLE capability (write): social-administration
admin.social.outbox.replay|TLE capability (write): social-administration
admin.social.read|TLE capability (read): social-administration
admin.timeline.read|TLE capability (read): timeline-administration
admin.timeline.replay|TLE capability (write): timeline-administration
admin.valkey.evict|TLE capability (write): valkey-administration
admin.valkey.read|TLE capability (read): valkey-administration
'

BUNDLES='
support|Player support and moderation: reads player-facing state, revokes player sessions, moderates lobby and social.
operator|Day-to-day live operations: support plus infrastructure reads, player corrections, queue and match interventions, content drafting and replays.
admin|Platform owner: every operator capability, including key rotation, kill switch, publishing and activation, destructive infrastructure actions and policy changes.
'

# bundle|capability, flattened (includes already resolved by the manifest).
MEMBERS='
support|admin.auth.read
support|admin.auth.sessions.read
support|admin.auth.sessions.revoke
support|admin.game.read
support|admin.lobby.moderate
support|admin.lobby.read
support|admin.matchmaking.read
support|admin.metadata.read
support|admin.notification.read
support|admin.player.read
support|admin.quest.read
support|admin.social.moderate
support|admin.social.read
support|admin.timeline.read
operator|admin.auth.read
operator|admin.auth.sessions.read
operator|admin.auth.sessions.revoke
operator|admin.game.match.terminate
operator|admin.game.read
operator|admin.game.snapshot.read
operator|admin.gamemaster.capacity.write
operator|admin.gamemaster.read
operator|admin.gateway.read
operator|admin.k8s.logs.read
operator|admin.k8s.read
operator|admin.lobby.moderate
operator|admin.lobby.read
operator|admin.lobby.session.disconnect
operator|admin.matchmaking.queue.intervene
operator|admin.matchmaking.read
operator|admin.matchmaking.replay
operator|admin.metadata.dependency.write
operator|admin.metadata.entity.create
operator|admin.metadata.entity.update
operator|admin.metadata.read
operator|admin.metadata.validate
operator|admin.nats.read
operator|admin.nats.replay
operator|admin.notification.preference.write
operator|admin.notification.read
operator|admin.notification.replay
operator|admin.player.economy.adjust
operator|admin.player.inventory.adjust
operator|admin.player.progression.adjust
operator|admin.player.read
operator|admin.quest.compensation.resolve
operator|admin.quest.control.write
operator|admin.quest.definition.create
operator|admin.quest.definition.update
operator|admin.quest.quarantine.replay
operator|admin.quest.read
operator|admin.social.guild.manage
operator|admin.social.moderate
operator|admin.social.outbox.replay
operator|admin.social.read
operator|admin.timeline.read
operator|admin.timeline.replay
operator|admin.valkey.read
admin|admin.auth.api_keys.manage
admin|admin.auth.keys.rotate
admin|admin.auth.kill_switch
admin|admin.auth.read
admin|admin.auth.sessions.read
admin|admin.auth.sessions.revoke
admin|admin.game.match.terminate
admin|admin.game.read
admin|admin.game.snapshot.read
admin|admin.gamemaster.capacity.write
admin|admin.gamemaster.pod.drain
admin|admin.gamemaster.read
admin|admin.gateway.policy.write
admin|admin.gateway.read
admin|admin.k8s.drain
admin|admin.k8s.logs.read
admin|admin.k8s.read
admin|admin.k8s.restart
admin|admin.k8s.scale
admin|admin.lobby.moderate
admin|admin.lobby.read
admin|admin.lobby.session.disconnect
admin|admin.matchmaking.queue.intervene
admin|admin.matchmaking.read
admin|admin.matchmaking.replay
admin|admin.metadata.activate
admin|admin.metadata.dependency.write
admin|admin.metadata.entity.create
admin|admin.metadata.entity.delete
admin|admin.metadata.entity.update
admin|admin.metadata.publish
admin|admin.metadata.read
admin|admin.metadata.retire
admin|admin.metadata.validate
admin|admin.nats.consumer.manage
admin|admin.nats.read
admin|admin.nats.replay
admin|admin.notification.preference.write
admin|admin.notification.read
admin|admin.notification.replay
admin|admin.notification.template.write
admin|admin.player.economy.adjust
admin|admin.player.inventory.adjust
admin|admin.player.progression.adjust
admin|admin.player.read
admin|admin.quest.compensation.resolve
admin|admin.quest.control.write
admin|admin.quest.definition.activate
admin|admin.quest.definition.create
admin|admin.quest.definition.delete
admin|admin.quest.definition.publish
admin|admin.quest.definition.update
admin|admin.quest.migration.execute
admin|admin.quest.quarantine.replay
admin|admin.quest.read
admin|admin.security.rate_limit.write
admin|admin.social.guild.manage
admin|admin.social.moderate
admin|admin.social.outbox.replay
admin|admin.social.read
admin|admin.timeline.read
admin|admin.timeline.replay
admin|admin.valkey.evict
admin|admin.valkey.read
'

# kcadm never gets the script's stdin: this script itself arrives on stdin.
kc() { "$K" "$@" -r "$REALM" --config "$C" </dev/null; }
kc_body() { "$K" "$@" -r "$REALM" --config "$C"; }

# Run a mutation in apply mode; only describe it in dry-run mode.
change() {
  msg=$1; shift
  if [ "$MODE" = apply ]; then
    echo "apply: $msg"
    "$@" >/dev/null
  else
    echo "would: $msg"
  fi
}

lines() { printf '%s\n' "$1" | grep -v '^$'; }

KC_CLI_PASSWORD="$KC_BOOTSTRAP_ADMIN_PASSWORD" "$K" config credentials \
  --server http://localhost:8080 --realm master \
  --user "$KC_BOOTSTRAP_ADMIN_USERNAME" --config "$C" >/dev/null
echo "mode: $MODE, realm: $REALM, client: $CLIENT_ID"

lines "$CAPABILITIES" | cut -d'|' -f1 | sort > "$W/want-caps"
lines "$BUNDLES" | cut -d'|' -f1 | sort > "$W/want-bundles"
sort "$W/want-caps" "$W/want-bundles" > "$W/want-roles"

# --- 1. client -------------------------------------------------------------
client_uuid() {
  # Exact match on clientId; duplicates abort.
  kc get clients -q "clientId=$CLIENT_ID" --fields id,clientId --format csv --noquotes \
    | grep ",$CLIENT_ID\$" | cut -d, -f1 > "$W/client"
  n=$(wc -l < "$W/client")
  if [ "$n" -gt 1 ]; then echo "duplicate clients named $CLIENT_ID" >&2; exit 1; fi
  cat "$W/client"
}

CU=$(client_uuid)
if [ -z "$CU" ]; then
  change "create confidential client $CLIENT_ID" kc create clients \
    -s "clientId=$CLIENT_ID" -s "name=$CLIENT_NAME" -s protocol=openid-connect \
    -s enabled=true -s publicClient=false -s clientAuthenticatorType=client-secret \
    -s standardFlowEnabled=true -s implicitFlowEnabled=false \
    -s directAccessGrantsEnabled=false -s serviceAccountsEnabled=false \
    -s 'redirectUris=[]' -s 'webOrigins=[]'
  [ "$MODE" = apply ] && CU=$(client_uuid)
else
  echo "ok: client $CLIENT_ID exists"
fi

current_roles() {
  if [ -n "$CU" ]; then
    kc get "clients/$CU/roles" --fields name --format csv --noquotes | sort
  fi
}

# --- 2 + 3a. capability and bundle roles ------------------------------------
current_roles > "$W/have-roles"
{ lines "$CAPABILITIES"; lines "$BUNDLES"; } | while IFS='|' read -r name desc; do
  if grep -Fxq "$name" "$W/have-roles"; then continue; fi
  change "create client role $name" kc create "clients/$CU/roles" -s "name=$name" -s "description=$desc"
done
current_roles > "$W/have-roles"
grep -Fxv -f "$W/want-roles" "$W/have-roles" > "$W/extra-roles" || true
while read -r name; do echo "WARN: client role $name is not in the manifest (left in place)"; done < "$W/extra-roles"

# --- 3b. composite members ---------------------------------------------------
role_id() {
  kc get "clients/$CU/roles/$1" --fields id --format csv --noquotes
}

while read -r bundle; do
  lines "$MEMBERS" | grep "^$bundle|" | cut -d'|' -f2 | sort > "$W/want-$bundle"
  if [ -n "$CU" ] && grep -Fxq "$bundle" "$W/have-roles"; then
    kc get "clients/$CU/roles/$bundle/composites" --fields name --format csv --noquotes | sort > "$W/have-$bundle"
  else
    : > "$W/have-$bundle"
  fi
  grep -Fxv -f "$W/have-$bundle" "$W/want-$bundle" > "$W/missing-$bundle" || true
  grep -Fxv -f "$W/want-$bundle" "$W/have-$bundle" > "$W/extra-$bundle" || true
  missing=$(wc -l < "$W/missing-$bundle")
  if [ "$missing" -eq 0 ]; then
    echo "ok: $bundle holds all $(wc -l < "$W/want-$bundle") members"
  elif [ "$MODE" = apply ]; then
    body='['
    sep=
    while read -r cap; do
      body="$body$sep{\"id\":\"$(role_id "$cap")\",\"name\":\"$cap\"}"
      sep=,
    done < "$W/missing-$bundle"
    body="$body]"
    echo "apply: add $missing members to composite $bundle"
    printf '%s' "$body" | kc_body create "clients/$CU/roles/$bundle/composites" -f - >/dev/null
  else
    echo "would: add $missing members to composite $bundle"
  fi
  while read -r name; do echo "WARN: composite $bundle has extra member $name (left in place)"; done < "$W/extra-$bundle"
done < "$W/want-bundles"

# --- 4. unused realm roles ---------------------------------------------------
kc get roles --fields name --format csv --noquotes > "$W/realm-roles"
kc get "roles/default-roles-$REALM/composites" --fields name --format csv --noquotes > "$W/default-roles" 2>/dev/null || : > "$W/default-roles"
for r in support operator; do
  if ! grep -Fxq "$r" "$W/realm-roles"; then echo "ok: no realm role $r"; continue; fi
  composite=$(kc get "roles/$r" --fields composite --format csv --noquotes)
  users=$(kc get "roles/$r/users" --fields id --format csv --noquotes | grep -c . || true)
  groups=$(kc get "roles/$r/groups" --fields id --format csv --noquotes | grep -c . || true)
  if [ "$composite" != false ] || [ "$users" -ne 0 ] || [ "$groups" -ne 0 ] || grep -Fxq "$r" "$W/default-roles"; then
    echo "SKIP: realm role $r is in use (composite=$composite users=$users groups=$groups); remove it by hand if intended"
  else
    change "delete unused realm role $r" kc delete "roles/$r"
  fi
done

# --- 5. verify -----------------------------------------------------------------
if [ "$MODE" = dry-run ]; then
  echo "dry run complete; nothing was changed"
  exit 0
fi
status=0
current_roles > "$W/have-roles"
if grep -Fxv -f "$W/have-roles" "$W/want-roles" > "$W/still-missing"; then
  echo "FAIL: roles still missing: $(tr '\n' ' ' < "$W/still-missing")"; status=1
fi
while read -r bundle; do
  kc get "clients/$CU/roles/$bundle/composites" --fields name --format csv --noquotes | sort > "$W/have-$bundle"
  if [ "$(cat "$W/want-$bundle")" != "$(cat "$W/have-$bundle")" ]; then
    echo "FAIL: composite $bundle differs from the manifest"; status=1
  fi
done < "$W/want-bundles"
[ "$status" -eq 0 ] && echo "verified: $(wc -l < "$W/want-caps") capability roles and $(wc -l < "$W/want-bundles") composites match the manifest"
exit "$status"
