apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tle-dev
resources:
  - vault-secrets.yaml
  - networkpolicy.yaml
  - edge-config.yaml
  - datastores.yaml
  - postgres-job.yaml
